const axios = require('axios');

const stores =    [
    {
        "id": "1",
        "name": "Techno Stationery Pins Maritimes",
        "country": "DZ",
        "city": "Alger",
        "zip": "16058",
        "address": "Cite les mandarines lot N 300 pins maritime, Mohammadia",
        "status": "1",
        "lat": "36.73331257",
        "lng": "3.16928744",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "874",
        "description": "<style>#html-body [data-pb-style=P6KM9KI]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"P6KM9KI\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\">Techno Pins Maritimes : (Sarl TM Stationery), située dans le quartier des Mandarines, qui est le pôle papeteries d’Alger, c’est l’un des grands magasins Techno, le plus grands sur Alger, avec une surface de 510 m², sur deux niveaux, qui vous permet un assortiment large des gammes papeterie, Pour les Clients Entreprise « B2B et Consommateur Final « B2C »<\/div><\/div><\/div>",
        "phone": "+213(0) 5 50 94 10 11 \/ +213(0) 5 60 05 99 98 \/  +213(0) 5 55 62 82 69",
        "email": "techno.pinsmaritimes@techno-dz.com",
        "website": "https:\/\/web.facebook.com\/profile.php?id=100087678493201",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "1",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Pins-Maritimes",
        "meta_title": null,
        "meta_description": "Techno Pins Maritimes :  (Sarl TM Stationery), située dans le quartier des Mandarines, qui est le pôle papeteries d’Alger, c’est l’un des grands magasins Techno, le plus grands sur Alger, avec une surface de 510 m², sur deux niveaux, qui vous permet un assortiment large des gammes papeterie, Pour les Clients Entreprise « B2B et Consommateur Final « B2C »",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "2",
        "name": "Techno Stationery Hydra",
        "country": "DZ",
        "city": "Alger",
        "zip": "16000",
        "address": "4 Chemin Sidi Yahia, Hydra",
        "status": "1",
        "lat": "36.73812745",
        "lng": "3.04355447",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "874",
        "description": "<style>#html-body [data-pb-style=OLJY546]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"OLJY546\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Hydra (Sarl Hydra Stationery), est votre meilleure adresse à Hydra et ses alentours pour faire vos achats Bureautique, scolaire ou beaux-arts, que vous soyez professionnel ou particulier, un accueil chaleureux vous attend. Techno Hydra se situe sur l’intersection du chemin Sidi Yahia et le chemin Said Hamdine et dispose de deux entrées à partir des deux chemins avec une superficie de 240 m².<\/p><\/div><\/div><\/div>",
        "phone": "+213 555 09 03 96",
        "email": "techno.hydra@techno-dz.com",
        "website": "https:\/\/www.facebook.com\/Techno.Stationery.Hydra",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":true,\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "2",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Hydra",
        "meta_title": null,
        "meta_description": "Techno Hydra (Sarl Hydra Stationery), est votre meilleure adresse à Hydra et ses alentours pour faire vos achats Bureautique, scolaire ou beaux-arts, que vous soyez professionnel ou particulier, un accueil chaleureux vous attend. Techno Hydra se situe sur l’intersection du chemin Sidi Yahia et le chemin Said Hamdine et dispose de deux entrées à partir des deux chemins avec une superficie de 240 m².",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "3",
        "name": "Techno Stationery Ouled Fayet",
        "country": "DZ",
        "city": "Alger",
        "zip": "16094",
        "address": "06 Rue Kouchi Ahmed، Ouled Fayet",
        "status": "1",
        "lat": "36.73635709",
        "lng": "2.95079410",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "874",
        "description": "<style>#html-body [data-pb-style=XR57H3Q]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"XR57H3Q\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Ouled Fayet (Sarl Dounia Papéterie) se situe en plein ville d’Ouled Fayet sur la rue Ahmed KOUCHI, pas loin du bureau de Poste, un magasin petit en surface (127 m²) grand dans son offre, vous permet de découvrir l’essentiel des gamme Bureautique, Scolaire, Beaux-Arts et Loisir Créatif.<\/p><\/div><\/div><\/div>",
        "phone": "+213 560 02 81 82",
        "email": "techno.ouledfayet@techno-dz.com",
        "website": "https:\/\/www.facebook.com\/techno.OuledFayet",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "3",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno Ouled Fayet",
        "meta_title": null,
        "meta_description": "Techno Ouled Fayet (Sarl Dounia Papéterie) se situe en plein ville d’Ouled Fayet sur la rue Ahmed KOUCHI, pas loin du bureau de Poste, un magasin petit en surface (127 m²) grand dans son offre, vous permet de découvrir l’essentiel des gamme Bureautique, Scolaire, Beaux-Arts et Loisir Créatif.",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "4",
        "name": "Techno Stationery Ain Benian",
        "country": "DZ",
        "city": "Alger",
        "zip": "16018",
        "address": "Lot chardonne mer la fontaine route nationale N 11 Ain Benian",
        "status": "1",
        "lat": "36.79220809",
        "lng": "2.90354146",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "874",
        "description": "<style>#html-body [data-pb-style=MVJH87V]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"MVJH87V\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Ain Benian (Sarl Techno Stationery) situé sur la Route Nationale N° 11, Plage de la Fontaine, à la sortie de Ain Benian en direction de Staoueli, avec une surface de 350 m², sur deux niveau (RDC et Sous Sol), Stationnement disponible; adresse idéale pour vos achats Bureautique, scolaire, Beaux-Arts et loisir créatif.<\/p><\/div><\/div><\/div>",
        "phone": "+213 555 04 43 43 ",
        "email": "techno.ainbenian@techno-dz.com",
        "website": "https:\/\/www.facebook.com\/Techno.Ain.Beniane",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "4",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Ain El Benian",
        "meta_title": null,
        "meta_description": "Techno Ain Benian (Sarl Techno Stationery) situé sur la Route Nationale N° 11, Plage de la Fontaine, à la sortie de Ain Benian en direction de Staoueli, avec une surface de 350 m², sur deux niveau (RDC et Sous Sol), Stationnement disponible; adresse idéale pour vos achats Bureautique, scolaire, Beaux-Arts et loisir créatif.",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "5",
        "name": "Techno Stationery Draria",
        "country": "DZ",
        "city": "Alger",
        "zip": "16050",
        "address": "Lot n 117, Chemin des Cretes, Draria",
        "status": "1",
        "lat": "36.71983348",
        "lng": "2.99468308",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "874",
        "description": "<style>#html-body [data-pb-style=DEP95PI]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"DEP95PI\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Draria (Sarl Draria Stationery) se situe devant le nouveau siège de l’APC de Draria, au niveau du chemin des crêtes, votre magasin est sur deux niveaux avec une superficie de 280 m², vous permet de découvrir une belle variété de produits bureau, scolaire, beaux-arts et loisirs créatif, avec des ateliers d’éveil artistique pour enfants et adultes, un bon accueil et prise en charge vous attend.<\/p><\/div><\/div><\/div>",
        "phone": "+213(0) 5 60 53 01 05 \/ +213(0) 5 61 97 77 88",
        "email": "techno.draria@techno-dz.com",
        "website": "https:\/\/www.facebook.com\/technodraria",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":true,\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "5",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Stationery-Draria",
        "meta_title": null,
        "meta_description": "Techno Draria (Sarl Draria Stationery) se situe devant le nouveau siège de l’APC de Draria, au niveau du chemin des crêtes, votre magasin est sur deux niveaux avec une superficie de 280 m², vous permet de découvrir une belle variété de produits bureau, scolaire, beaux-arts et loisirs créatif, avec des ateliers d’éveil artistique pour enfants et adultes, un bon accueil et prise en charge vous attend.",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "6",
        "name": "Techno Stationery Cheraga",
        "country": "DZ",
        "city": "Alger",
        "zip": "16014",
        "address": "Lot n1 Amara 02, Route de Ouled Fayet، Chéraga",
        "status": "1",
        "lat": "36.75599869",
        "lng": "2.95157886",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "874",
        "description": "<style>#html-body [data-pb-style=DAROQU8]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"DAROQU8\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Cheraga (Sarl Techno Stationery) se situe sur le rondpoint du lotissement Amara avec une superficie de 290 m² vous permet de découvrir une belle variété de produits bureau, scolaire, beaux-arts et loisirs créatif, avec des ateliers d’éveil artistique pour enfants et adultes, un bon accueil et prise en charge vous attend.<\/p><\/div><\/div><\/div>",
        "phone": " +213 560 95 69 06",
        "email": "techno.cheraga@techno-dz.com",
        "website": "https:\/\/www.facebook.com\/Techno.Cheraga",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "6",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Stationery-Cheraga",
        "meta_title": null,
        "meta_description": "Techno Cheraga (Sarl Techno Stationery) se situe sur le rondpoint du lotissement Amara avec une superficie de 290 m² vous permet de découvrir une belle variété de produits bureau, scolaire, beaux-arts et loisirs créatif, avec des ateliers d’éveil artistique pour enfants et adultes, un bon accueil et prise en charge vous attend.",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "7",
        "name": "Techno Stationery Dely Ibrahim",
        "country": "DZ",
        "city": "Alger",
        "zip": "16302",
        "address": "Rue Dely Brahim Lot 03, 06, Chéraga",
        "status": "1",
        "lat": "36.75710586",
        "lng": "2.96492513",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "874",
        "description": "<style>#html-body [data-pb-style=L6PM7C7]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"L6PM7C7\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Dely Brahim (Sarl Dely Brahim Stationery) se situe sur le boulevard Ahcen TELLA, pas loin de la place El Kods, votre magasin est sur deux niveau avec une superficie totale de 300 m² avec un grand parking derrière le magasin pour faire votre shopping à l’aise, un bon accueil vous attends et un service dédier aux entreprises.<\/p><\/div><\/div><\/div>",
        "phone": "+213 560 85 42 39",
        "email": "technodelybrahim@techno-dz.com",
        "website": "https:\/\/www.facebook.com\/Techno.Dely.Brahim",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":true,\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "7",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Stationery-Dely-Ibrahim",
        "meta_title": null,
        "meta_description": "Techno Dely Brahim (Sarl Dely Brahim Stationery) se situe sur le boulevard Ahcen TELLA, pas loin de la place El Kods, votre magasin est sur deux niveau avec une superficie totale de 300 m² avec un grand parking derrière le magasin pour faire votre shopping à l’aise, un bon accueil vous attends et un service dédier aux entreprises.",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "8",
        "name": "Techno Stationery Rouiba",
        "country": "DZ",
        "city": "Alger",
        "zip": "16017",
        "address": "01, Rue Ali khodja, Rouiba",
        "status": "1",
        "lat": "36.73817708",
        "lng": "3.28256124",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "874",
        "description": "<style>#html-body [data-pb-style=X4H8EB6]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"X4H8EB6\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Rouiba (Sarl Creative Office), a ouvert ses portes à nos clients de rouiba et environs le mois de mai 2016, il se situe au plein centre-ville de Rouiba, sur une surface de 80m², il vous promet un accueil chaleureux et un service rapide<\/p><\/div><\/div><\/div>",
        "phone": "+213 560 09 40 74",
        "email": "technorouiba@techno-dz.com",
        "website": "https:\/\/www.facebook.com\/Techno.Rouiba",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "8",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Stationery-Rouiba",
        "meta_title": null,
        "meta_description": "Techno Rouiba (Sarl Creative Office), a ouvert ses portes à nos clients de rouiba et environs le mois de mai 2016, il se situe au plein centre-ville de Rouiba, sur une surface de 80m², il vous promet un accueil chaleureux et un service rapide",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "9",
        "name": "Techno Stationery Blida",
        "country": "DZ",
        "city": "Blida",
        "zip": "9000",
        "address": "Lotissement Ben Boulaid 01 Local n°02",
        "status": "1",
        "lat": "36.48524798",
        "lng": "2.83374921",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "867",
        "description": "<style>#html-body [data-pb-style=S650YVQ]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"S650YVQ\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Blida (Sarl Blida Stationery) se situe sur le boulevard Mohamed BOUDIAF, connue par le Boulevard des 20 mètres, près de la mosquée Ben Djelloul, sur une superficie de 260 m² en deux niveaux (RDC et Sous Sole) vous offre un service adopté à vos besoins et réponds à vos attentes<\/p><\/div><\/div><\/div>",
        "phone": "+213 561 67 85 80",
        "email": "techno.blida@techno-dz.com",
        "website": "https:\/\/www.facebook.com\/Techno.Blida",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "9",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Stationery-Blida",
        "meta_title": null,
        "meta_description": "Techno Blida (Sarl Blida Stationery) se situe sur le boulevard Mohamed BOUDIAF, connue par le Boulevard des 20 mètres, près de la mosquée Ben Djelloul, sur une superficie de 260 m² en deux niveaux (RDC et Sous Sole) vous offre un service adopté à vos besoins et réponds à vos attentes",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "10",
        "name": "Techno Stationery Boumerdes",
        "country": "DZ",
        "city": "Boumerdés",
        "zip": "35000",
        "address": "Route Nationale n° 24 Cité 44 Lgts, Bâtiment 02 lot 03",
        "status": "1",
        "lat": "36.75032213",
        "lng": "3.47341645",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "893",
        "description": "<style>#html-body [data-pb-style=STVYG92]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"STVYG92\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Boumerdes (Sarl Boumerdes Office) a ouvert ses portes le mois d’avril 2018, elle renforce sa position comme une destination des consommateurs de la papèterie, qu’ils soient professionnels ou particuliers, Techno Boumerdes vous promet un bon accueil et une bonne prise en charge de vos besoins, Située sur la route de Tidjellabine, juste après la localité de Foes.&nbsp;<\/p><\/div><\/div><\/div>",
        "phone": "+213(0) 5 60 67 24 86 \/ +213(0) 5 40 35 36 01",
        "email": "techno.boumerdes@techno-dz.com",
        "website": "https:\/\/www.facebook.com\/Techno-Stationery-Boumerdes-103285164806700",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "10",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Stationery-Boumerdes",
        "meta_title": null,
        "meta_description": "Techno Boumerdes (Sarl Boumerdes Office) a ouvert ses portes le mois d’avril 2018, elle renforce sa position comme une destination des consommateurs de la papèterie, qu’ils soient professionnels ou particuliers, Techno Boumerdes vous promet un bon accueil et une bonne prise en charge de vos besoins, Située sur la route de Tidjellabine, juste après la localité de Foes. ",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "11",
        "name": "Techno Stationery Bir El Djir",
        "country": "DZ",
        "city": "Oran",
        "zip": "31000",
        "address": "38, Boulevard Milinium 1, Bir El Djir",
        "status": "1",
        "lat": "35.72632089",
        "lng": "-0.57114915",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "889",
        "description": "<style>#html-body [data-pb-style=J0EEKOB]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"J0EEKOB\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Bir El Djir (Sarl Bahia Stationery) se situe sur le boulevard Millenium à Bir el Djir, votre magasin référence pour le coté est d’Oran pour faire vos achats Bureautique, scolaire, Beaux-Arts et Loisir Créatif, il s’étends sur 600m² et vous promet un accueil de qualité .<\/p><\/div><\/div><\/div>",
        "phone": "+213 560 83 20 67",
        "email": "techno.bireldjir@techno-dz.com ",
        "website": "https:\/\/www.facebook.com\/technobireldjir",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "11",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Stationery-Bir-El-Djir",
        "meta_title": null,
        "meta_description": "Techno Bir El Djir (Sarl Bahia Stationery) se situe sur le boulevard Millenium à Bir el Djir, votre magasin référence pour le coté est d’Oran pour faire vos achats Bureautique, scolaire, Beaux-Arts et Loisir Créatif, il s’étends sur 600m² et vous promet un accueil de qualité .",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "12",
        "name": "Techno Stationery Oran",
        "country": "DZ",
        "city": "Oran",
        "zip": "31000",
        "address": "Lot n° 13 & 14 Coopérative Ezzohour, Cité Dar El Beida",
        "status": "1",
        "lat": "35.69671255",
        "lng": "-0.60644909",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "889",
        "description": "<style>#html-body [data-pb-style=Y52M4Q9]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"Y52M4Q9\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Oran (Sarl Smart Office) se situe face à la Grande Mosquée Ibn Badis, c’est le plus grand Magasin Techno, il s’étale sur 1200 m² en deux niveaux, une bonne prise en charge vous attend, que vous soyez professionnel ou particulier, avec des ateliers d’éveil artistique pour enfants et adultes.<\/p><\/div><\/div><\/div>",
        "phone": "+213(0) 5 60 21 87 98\/ +213(0) 5 60 21 71 44",
        "email": "techno.oran@techno-dz.com",
        "website": "https:\/\/www.facebook.com\/Techno.Oran",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "12",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Stationery-Oran",
        "meta_title": null,
        "meta_description": "Techno Oran (Sarl Smart Office) se situe face à la Grande Mosquée Ibn Badis, c’est le plus grand Magasin Techno, il s’étale sur 1200 m² en deux niveaux, une bonne prise en charge vous attend, que vous soyez professionnel ou particulier, avec des ateliers d’éveil artistique pour enfants et adultes.",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "13",
        "name": "Techno Stationery Mostaganem",
        "country": "DZ",
        "city": "Mostaganem",
        "zip": "27000",
        "address": "Cité Colonel Amirouche Boulevard Ouled Aissa, Belkacem n°36",
        "status": "1",
        "lat": "35.93015026",
        "lng": "0.08328510",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "885",
        "description": "<style>#html-body [data-pb-style=I9QQ881]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"I9QQ881\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Mostaganem (Sarl Mostaganem Office) votre magasin de papèterie à Mostaganem, situé sur le Boulevard Ouled Aissa Belkacem, sur une surface de 500 m², vous permet de découvrir toute l’offre papèterie (Bureau, Scolaire, Beaux-Arts et Loisirs Créatif) une équipe dynamique et motivée pour bien vous accueillir et servir que vous soyez professionnel ou particulier Techno réponds à vos besoins.<\/p><\/div><\/div><\/div>",
        "phone": " +213 560 975 122 \/ +213 560 939 161",
        "email": "techno.mostaganem@techno-dz.com  ",
        "website": "https:\/\/www.facebook.com\/Techno.Stationery.Mostaganem",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "13",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Stationery-Mostaganem",
        "meta_title": null,
        "meta_description": "Techno Mostaganem (Sarl Mostaganem Office) votre magasin de papèterie à Mostaganem, situé sur le Boulevard Ouled Aissa Belkacem, sur une surface de 500 m², vous permet de découvrir toute l’offre papèterie (Bureau, Scolaire, Beaux-Arts et Loisirs Créatif) une équipe dynamique et motivée pour bien vous accueillir et servir que vous soyez professionnel ou particulier Techno réponds à vos besoins.",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "14",
        "name": "Techno Stationery Sidi Belabes",
        "country": "DZ",
        "city": "Sidi Bel Abbés",
        "zip": "22000",
        "address": "19 Boulevard Mohammed Khemisti",
        "status": "1",
        "lat": "35.18604692",
        "lng": "-0.63137285",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "880",
        "description": "<style>#html-body [data-pb-style=B3VSBO2]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"B3VSBO2\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Belabes (Sarl Success Stationery) situé sur le Boulevard Mohamed KHEMISTI (Trik Ennadjah) enface Lycée Ennadjah, avec une surface de 200 m², c’est votre meilleure adresse pour vos achats Bureautique, scolaire, Beaux-Arts et loisir créatif à Belabes.<\/p><\/div><\/div><\/div>",
        "phone": "+213 561 78 97 56",
        "email": "techno.belabes@techno-dz.com ",
        "website": "https:\/\/www.facebook.com\/Techno.SidiBelAbbes",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "14",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno Stationery Sidi Belabes",
        "meta_title": null,
        "meta_description": "Techno Belabes (Sarl Success Stationery) situé sur le Boulevard Mohamed KHEMISTI (Trik Ennadjah) enface Lycée Ennadjah, avec une surface de 200 m², c’est votre meilleure adresse pour vos achats Bureautique, scolaire, Beaux-Arts et loisir créatif à Belabes.",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "15",
        "name": "Techno Stationery Setif",
        "country": "DZ",
        "city": "Sétif",
        "zip": "19000",
        "address": "Promotion Immo Lyazid Amrani, Bt n°1 Ain Tbint",
        "status": "1",
        "lat": "36.18533720",
        "lng": "5.43915562",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "877",
        "description": "<style>#html-body [data-pb-style=CIVVIET]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"CIVVIET\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Sétif (Sarl Djemila Office), a concrétiser le sens de sa raison sociale «&nbsp;Djemila&nbsp;» une très belle Papèterie qui offre aux Sétifiens un large choix de produits, inaugurée le mois d’avril 2011, <br>Votre point de vente est situé dans la localité de T’bint pas loin du rondpoint les tours, Techno Sétif dispose d’un grand espace de stationnement et vous promet un sourire en sortant.&nbsp;<\/p><\/div><\/div><\/div>",
        "phone": "+213 560 06 66 50",
        "email": "techno.setif@techno-dz.com ",
        "website": "https:\/\/www.facebook.com\/Techno.Stationery.Setif",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":true,\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "15",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Stationery-Setif",
        "meta_title": null,
        "meta_description": "\"Techno Sétif (Sarl Djemila Office), a concrétiser le sens de sa raison sociale « Djemila » une très belle Papèterie qui offre aux Sétifiens un large choix de produits, inaugurée le mois d’avril 2011, \r\nVotre point de vente est situé dans la localité de T’bint pas loin du rondpoint les tours, Techno Sétif dispose d’un grand espace de stationnement et vous promet un sourire en sortant. \"",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "16",
        "name": "Techno Stationery Annaba",
        "country": "DZ",
        "city": "Annaba",
        "zip": "23000",
        "address": "31, Rue Saouli Abdelkader",
        "status": "1",
        "lat": "36.90565446",
        "lng": "7.75444854",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "881",
        "description": "<style>#html-body [data-pb-style=EGYLMKY]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"EGYLMKY\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Annaba est le meilleur endroit pour vos achats Bureautique, Scolaire , Beaux Arts et Loisir créatif au niveau de la Wilaya de Annaba.<br>Nos portes sont ouvertes pour vous accueillir et vous servir avec plaisir à 31 Bd Saouli Abdelkader.<br>vous êtes les bienvenus<\/p><\/div><\/div><\/div>",
        "phone": "+213 560 45 81 24",
        "email": "techno.annaba@techno-dz.com",
        "website": "https:\/\/www.facebook.com\/Techno.Stationery.annaba",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "16",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Stationery-Annaba",
        "meta_title": null,
        "meta_description": "\"Techno Annaba est le meilleur endroit pour vos achats Bureautique, Scolaire , Beaux Arts et Loisir créatif au niveau de la Wilaya de Annaba.\r\nNos portes sont ouvertes pour vous accueillir et vous servir avec plaisir à 31 Bd Saouli Abdelkader.\r\nvous êtes les bienvenus\"",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "17",
        "name": "Techno Stationery Constantine",
        "country": "DZ",
        "city": "Constantine",
        "zip": "25000",
        "address": "Unité de voisinage 05, Bâtiment n°01, Nouvelle Ville Ali Mendjeli",
        "status": "1",
        "lat": "36.26352956",
        "lng": "6.58422878",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "883",
        "description": "<style>#html-body [data-pb-style=E81Q35P]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"E81Q35P\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Inaugurer le mois d’avril 2019, Techno Constantine (Sarl The Best Stationery), a le plaisir de vous accueillir dans son espace qui s’étale sur 280 m² et qui est la papèterie qui a l’offre la plus complète au niveau de la Wilaya de Constantine, en plus de son emplacement pas loin du pôle universitaire, Techno Constantine se considère comme un auxiliaire pour le rayonnement de la science dans la cité de la science.<\/p><\/div><\/div><\/div>",
        "phone": "+213 556 69 96 30",
        "email": "techno.constantine@techno-dz.com ",
        "website": "https:\/\/www.facebook.com\/TECHNO.Constantine",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "17",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno Stationery Constantine",
        "meta_title": null,
        "meta_description": "Inaugurer le mois d’avril 2019, Techno Constantine (Sarl The Best Stationery), a le plaisir de vous accueillir dans son espace qui s’étale sur 280 m² et qui est la papèterie qui a l’offre la plus complète au niveau de la Wilaya de Constantine, en plus de son emplacement pas loin du pôle universitaire, Techno Constantine se considère comme un auxiliaire pour le rayonnement de la science dans la cité de la science.",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "18",
        "name": "Techno Stationery Djelfa",
        "country": "DZ",
        "city": "Djelfa",
        "zip": "17000",
        "address": "130, Rue Sidi Nayel",
        "status": "1",
        "lat": "34.66982861",
        "lng": "3.25046087",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "875",
        "description": "<style>#html-body [data-pb-style=G2RHTKC]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"G2RHTKC\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Djelfa (Sarl Djelfa Stationery) se situe sur la rue Sidi Nayel, sur une superficie de 200 m² vous permet de découvrir l’essentiel de l’offre Techno et vous garantie un accueil de qualité et un service adapté à vos besoins.<\/p><\/div><\/div><\/div>",
        "phone": "+213 561 80 01 17",
        "email": "techno.djelfa@techno-dz.com",
        "website": "https:\/\/www.facebook.com\/Techno-Stationery-Djelfa-102007531361266",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "18",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Stationery-Djelfa",
        "meta_title": null,
        "meta_description": "Techno Djelfa (Sarl Djelfa Stationery) se situe sur la rue Sidi Nayel, sur une superficie de 200 m² vous permet de découvrir l’essentiel de l’offre Techno et vous garantie un accueil de qualité et un service adapté à vos besoins.",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "19",
        "name": "Techno Stationery Batna",
        "country": "DZ",
        "city": "Batna",
        "zip": "5000",
        "address": "Lotissement Djerrou Dib Boulevard K L Route Biskra",
        "status": "1",
        "lat": "35.54028856",
        "lng": "6.15610920",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "863",
        "description": "<style>#html-body [data-pb-style=NC8NKFW]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"NC8NKFW\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Située dans la Wilaya Historique et capitale des Aurès berceau de la révolution de libération Nationale, Techno Batna (Sarl Batna Stationery) a ouvert ses portes le mois d’avril 2020, en plein crise du Covid-19, Techno Batna a pris sa part de révolte et s’est imposé dans des conditions difficiles comme une destination pour le shopping de produits bureautique, scolaire et beaux-arts&nbsp;; et profite de sa situation géographique sur la rue de Biskra à coté de l’université et de la cours de Justice, elle offre aussi un grand espace de stationnement pour ses Clients.<\/p><\/div><\/div><\/div>",
        "phone": "+213 770 06 14 96",
        "email": "techno.batna@techno-dz.com",
        "website": "https:\/\/www.facebook.com\/Techno.Batna",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "19",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Stationery-Batna",
        "meta_title": null,
        "meta_description": "Située dans la Wilaya Historique et capitale des Aurès berceau de la révolution de libération Nationale, Techno Batna (Sarl Batna Stationery) a ouvert ses portes le mois d’avril 2020, en plein crise du Covid-19, Techno Batna a pris sa part de révolte et s’est imposé dans des conditions difficiles comme une destination pour le shopping de produits bureautique, scolaire et beaux-arts ; et profite de sa situation géographique sur la rue de Biskra à coté de l’université et de la cours de Justice, elle offre aussi un grand espace de stationnement pour ses Clients.",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "20",
        "name": "Techno Stationery Ghardaia",
        "country": "DZ",
        "city": "Ghardaia",
        "zip": "47000",
        "address": "Rue du 05 Juillet, Bounoura",
        "status": "1",
        "lat": "32.47905598",
        "lng": "3.69431947",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "905",
        "description": "<style>#html-body [data-pb-style=V04DUMT]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"V04DUMT\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Ghardaïa (Sarl Bureau Magic) se situe sur la rue du 1er novembre pas loin du centre-ville de Ghardaïa, c’est la destination idéale pour vos achats Bureautique, scolaire, Beaux-Arts et Loisir Créatif, <br>Techno Ghardaïa s’est engagée à respecter l’architecture locale en déclinaison sa façade selon les exigences de l’Office de Protection et la Promotion de la Valée du M’Zab.<\/p><\/div><\/div><\/div>",
        "phone": " +213 560 02 89 33",
        "email": "techno.ghardaia@techno-dz.com ",
        "website": "https:\/\/www.facebook.com\/Techno.Ghardaia",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "20",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Stationery-Ghardaia",
        "meta_title": null,
        "meta_description": "\"Techno Ghardaïa (Sarl Bureau Magic) se situe sur la rue du 1er novembre pas loin du centre-ville de Ghardaïa, c’est la destination idéale pour vos achats Bureautique, scolaire, Beaux-Arts et Loisir Créatif, \r\nTechno Ghardaïa s’est engagée à respecter l’architecture locale en déclinaison sa façade selon les exigences de l’Office de Protection et la Promotion de la Valée du M’Zab.\"",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "21",
        "name": "Techno Stationery Béjaia",
        "country": "DZ",
        "city": "Béjaia",
        "zip": "06000",
        "address": "BT C, N°07, Cité EDIMCO, Bejaia ville",
        "status": "1",
        "lat": "36.74569115",
        "lng": "5.04874790",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "864",
        "description": "<style>#html-body [data-pb-style=XU99CHK]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"XU99CHK\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Bejaia (Sarl Bejaia Stationery) situé au BT C, N°07, Cité EDIMCO, Bejaia ville, wilaya de Bejaia, avec une surface de 300 m², sur deux niveau (RDC et Sous Sol), Stationnement disponible; adresse idéale pour vos achats Bureautique, scolaire, Beaux-Arts et loisir créatif.<\/p><\/div><\/div><\/div>",
        "phone": "+213 550 79 82 97",
        "email": "techno.bejaia@techno-dz.com",
        "website": "https:\/\/www.facebook.com\/Techno.Bejaia",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":true,\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "21",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-bejaia",
        "meta_title": null,
        "meta_description": "Techno Bejaia (Sarl Bejaia Stationery) situé au BT C, N°07, Cité EDIMCO, Bejaia ville, wilaya de Bejaia, avec une surface de 300 m², sur deux niveau (RDC et Sous Sol), Stationnement disponible; adresse idéale pour vos achats Bureautique, scolaire, Beaux-Arts et loisir créatif.",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "22",
        "name": "Techno Stationery Bordj Bou Arreridj",
        "country": "DZ",
        "city": "Bordj Bou Arreridj",
        "zip": "34000 ",
        "address": "10, Rue Abdelkader El Bariki, Bordj Bou Arreridj",
        "status": "1",
        "lat": "36.06760210",
        "lng": "4.76053380",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "892",
        "description": "<style>#html-body [data-pb-style=OPVKSIL]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"OPVKSIL\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Bordj Bou Arreridj (Sarl The Best Market Stationery) <br>Vient de marquer sa présence comme 22ème magasin de Techno sur le territoire nationale le 07 Aout 2022. <br>Situé au niveau du 10, Rue Abdelkader El Bariki, Bordj Bou Arreridj, ou comme connue au niveau d’El Bordj par Rue Abane Ramdane Bab El Sougue en face Sonelgaz.<br>Magasin de 600 m² répartit en deux niveaux (RDC et Sous-Sol), qui vous permet un One Stop pour tous vos achats de Papeterie, à savoir la Bureautique, le Scolaire, les Loisirs Créatifs et Beaux-arts, pour ses Clients Entreprise « B2B » et Consommateurs Finaux « B2C ».<\/p><\/div><\/div><\/div>",
        "phone": "+213 555 51 86 66",
        "email": "techno.bba@techno-dz.com",
        "website": "https:\/\/www.facebook.com\/Techno.Stationery.Bordj.Bou.Arreridj",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":true,\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "43",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Bordj-Bou-Arreridj",
        "meta_title": null,
        "meta_description": "\"Techno Bordj Bou Arreridj (Sarl The Best Market Stationery) \r\nVient de marquer sa présence comme 22ème magasin de Techno sur le territoire nationale le 07 Aout 2022. \r\nSitué au niveau du 10, Rue Abdelkader El Bariki, Bordj Bou Arreridj, ou comme connue au niveau d’El Bordj par Rue Abane Ramdane Bab El Sougue en face Sonelgaz.\r\nMagasin de 600 m² répartit en deux niveaux (RDC et Sous-Sol), qui vous permet un One Stop pour tous vos achats de Papeterie, à savoir la Bureautique, le Scolaire, les Loisirs Créatifs et Beaux-arts, pour ses Clients Entreprise « B2B » et Consommateurs Finaux « B2C ».\"",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "23",
        "name": "Techno Stationery Ouargla",
        "country": "DZ",
        "city": "Ouargla",
        "zip": "30000",
        "address": "Avenue du 1er Novembre 1954, (ITAS) en face la Bibliothèque principale - Ouargla",
        "status": "1",
        "lat": "31.94210940",
        "lng": "5.30288750",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "888",
        "description": "<style>#html-body [data-pb-style=MI3ODUE]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"MI3ODUE\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><br><p>Techno Ouargla sur une superficie de 300m², est votre espace idéal pour vos achats bureautique, &nbsp;scolaire, beaux-arts et loisirs créatifs.&nbsp;<br>Vous avez un service B2B dédié aux entreprises, commande à distance et livraison à votre bureau.&nbsp;<br>Un espace pour les ateliers créatifs aux enfants et adultes avec un programme riche.&nbsp;<br>Techno Ouargla est située juste en face de la bibliothèque principale et le centre culturel islamique.&nbsp;<br>Nous serons honoré de vous servir.<\/p><\/div><div data-content-type=\"html\" data-appearance=\"default\" data-element=\"main\">&lt;a href=\"https:\/\/www.facebook.com\/Techno.Ouargla\" class=\"amlocator-link\" target=\"_blank\"&gt;\r\n    &lt;span class=\"amlocator-icon -website\" style=\"font-weight:bold\"&gt;Visitez nous sur Facebook&lt;\/span&gt;\r\n&lt;\/a&gt;&lt;br&gt;\r\n&lt;a href=\"https:\/\/www.instagram.com\/techno.ouargla\/\" class=\"amlocator-link\" target=\"_blank\"&gt;\r\n    &lt;span class=\"amlocator-icon -website\" style=\"font-weight:bold\"&gt;Visitez nous sur Instagram&lt;\/span&gt;\r\n&lt;\/a&gt;&lt;br&gt;\r\n&lt;a href=\"https:\/\/www.tiktok.com\/@techno_ouargla\" class=\"amlocator-link\" target=\"_blank\"&gt;\r\n    &lt;span class=\"amlocator-icon -website\" style=\"font-weight:bold\"&gt;Visitez nous sur Tiktok&lt;\/span&gt;\r\n&lt;\/a&gt;&lt;br&gt;<\/div><\/div><\/div>",
        "phone": "+213 560 34 77 68",
        "email": "techno.ouargla@techno-dz.com",
        "website": "https:\/\/www.facebook.com\/Techno.Ouargla",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "54",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Ouargla",
        "meta_title": null,
        "meta_description": "\"Techno Ouargla sur une superficie de 300m², est votre espace idéal pour vos achats bureautique,  scolaire, beaux-arts et loisirs créatifs. \r\nVous avez un service B2B dédié aux entreprises, commande à distance et livraison à votre bureau. \r\nUn espace pour les ateliers créatifs aux enfants et adultes avec un programme riche. \r\nTechno Ouargla est située juste en face de la bibliothèque principale et le centre culturel islamique. \r\nNous serons honoré de vous servir.\"\r\n",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "24",
        "name": "Techno Stationery Tiaret",
        "country": "DZ",
        "city": "Tiaret",
        "zip": "14000",
        "address": "Rond-point Zaaroura, Bt A, RC Bloc 17, Tiaret - 14036",
        "status": "1",
        "lat": "35.34828523",
        "lng": "1.31660456",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "872",
        "description": "<style>#html-body [data-pb-style=Q7S3KPN]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"Q7S3KPN\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><p>Techno Tiaret sur une superficie de 450m², est votre espace idéal pour vos achats bureautique, scolaire, beaux-arts et loisirs créatifs.&nbsp;<br>Vous avez un service B2B dédié aux entreprises, commande à distance et livraison à votre bureau.&nbsp;<br>Un espace pour les ateliers créatifs aux enfants et adultes avec un programme riche.&nbsp;<br>Techno Tiaret est située au rond point Zaaroura, près de l'université de Tiaret.&nbsp;<br>Nous serons honorés de vous servir.<\/p><\/div><\/div><\/div>",
        "phone": "+213 550 84 65 03",
        "email": "techno.tiaret@techno-dz.com  ",
        "website": "https:\/\/web.facebook.com\/techno.tiaret",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "55",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Stationery-Tiaret",
        "meta_title": null,
        "meta_description": "\"Techno Tiaret sur une superficie de 450m², est votre espace idéal pour vos achats bureautique, scolaire, beaux-arts et loisirs créatifs. \r\nVous avez un service B2B dédié aux entreprises, commande à distance et livraison à votre bureau. \r\nUn espace pour les ateliers créatifs aux enfants et adultes avec un programme riche. \r\nTechno Tiaret est située au rond point Zaaroura, près de l'université de Tiaret. \r\nNous serons honorés de vous servir.\"",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    },
    {
        "id": "25",
        "name": "Techno Stationery Laghouat",
        "country": "DZ",
        "city": "Laghouat",
        "zip": "3000",
        "address": "Cité El Makam Laghouat",
        "status": "1",
        "lat": "33.79655840",
        "lng": "2.85605990",
        "photo": null,
        "marker": null,
        "position": "0",
        "state": "861",
        "description": "<style>#html-body [data-pb-style=WJ2F1CL]{justify-content:flex-start;display:flex;flex-direction:column;background-position:left top;background-size:cover;background-repeat:no-repeat;background-attachment:scroll}<\/style><div data-content-type=\"row\" data-appearance=\"contained\" data-element=\"main\"><div data-enable-parallax=\"0\" data-parallax-speed=\"0.5\" data-background-images=\"{}\" data-background-type=\"image\" data-video-loop=\"true\" data-video-play-only-visible=\"true\" data-video-lazy-load=\"true\" data-video-fallback-src=\"\" data-element=\"inner\" data-pb-style=\"WJ2F1CL\"><div data-content-type=\"text\" data-appearance=\"default\" data-element=\"main\"><br><p>La wilaya de Laghouat accueille avec fierté notre nouveau point de vente : Techno Stationery Laghouat.<\/p>\r\n<p>Inauguré le 20 juin 2024, ce 25e magasin, s'étendant sur 350 m², offre une vaste gamme de fournitures Scolaires, Bureautiques, Beaux-arts, Techniques, Informatiques, Jouets éducatifs, Loisirs créatifs et Bricolage.<\/p>\r\n<p>Les clients peuvent également profiter d'un espace dédié aux services pour Entreprises et d'Ateliers créatifs pour enfants et adultes.<\/p>\r\n<p>Rejoignez notre grande famille et découvrez tout ce que Techno Stationery Laghouat propose aux habitants de la région.<\/p><\/div><div data-content-type=\"html\" data-appearance=\"default\" data-element=\"main\">&lt;a href=\"https:\/\/www.facebook.com\/profile.php?id=61558333116077\" class=\"amlocator-link\" target=\"_blank\"&gt;\r\n    &lt;span class=\"amlocator-icon -website\" style=\"font-weight:bold\"&gt;Visitez nous sur Facebook&lt;\/span&gt;\r\n&lt;\/a&gt;&lt;br&gt;\r\n&lt;a href=\"https:\/\/www.instagram.com\/techno.laghouat\/\" class=\"amlocator-link\" target=\"_blank\"&gt;\r\n    &lt;span class=\"amlocator-icon -website\" style=\"font-weight:bold\"&gt;Visitez nous sur Instagram&lt;\/span&gt;\r\n&lt;\/a&gt;&lt;br&gt;\r\n&lt;a href=\"https:\/\/www.tiktok.com\/@techno.laghouat\" class=\"amlocator-link\" target=\"_blank\"&gt;\r\n    &lt;span class=\"amlocator-icon -website\" style=\"font-weight:bold\"&gt;Visitez nous sur Tiktok&lt;\/span&gt;\r\n&lt;\/a&gt;&lt;br&gt;<\/div><\/div><\/div>",
        "phone": "+213 560 11 21 57",
        "email": "techno.laghouat@techno-dz.com  ",
        "website": "https:\/\/www.facebook.com\/profile.php?id=61558333116077",
        "category": null,
        "actions_serialized": "{\"type\":\"Magento\\\\CatalogRule\\\\Model\\\\Rule\\\\Condition\\\\Combine\",\"attribute\":null,\"operator\":null,\"value\":\"1\",\"is_value_processed\":null,\"aggregator\":\"all\"}",
        "store_img": "",
        "stores": ",0,",
        "schedule": "56",
        "marker_img": "",
        "show_schedule": "1",
        "url_key": "Techno-Stationery-Laghouat",
        "meta_title": null,
        "meta_description": "La wilaya de Laghouat accueille avec fierté notre nouveau point de vente : Techno Stationery Laghouat.\r\nInauguré le 20 juin 2024, ce 25e magasin, s'étendant sur 350 m², offre une vaste gamme de fournitures Scolaires, Bureautiques, Beaux-arts, Techniques, Informatiques, Jouets éducatifs, Loisirs créatifs et Bricolage.\r\nLes clients peuvent également profiter d'un espace dédié aux services pour Entreprises et d'Ateliers créatifs pour enfants et adultes.\r\nRejoignez notre grande famille et découvrez tout ce que Techno Stationery Laghouat propose aux habitants de la région.",
        "meta_robots": "INDEX,FOLLOW",
        "short_description": null,
        "canonical_url": null,
        "condition_type": "1",
        "curbside_enabled": "0",
        "curbside_conditions_text": null
    }
]

const magentoUrl = 'https://technostationery.com/rest/V1/integration/admin/token';
 
const magentoCredentials = {
  username: 'islam.ba',
  password: 'tP5WTKPdJRYe2db'
};

async function createMagentoSources() {
  try {
    // Get Magento Admin Token
    const tokenResponse = await axios.post(magentoUrl, magentoCredentials);
    const token = tokenResponse.data;

    const config = {
      headers: {
        Authorization: `Bearer ${token}`
      }
    };
console.log('Magento Admin Token:', token);
    // Post each store as a source
    for (const store of stores) {
        const sourceData = {
            source: {
              source_code: store.name.replace(/\s+/g, ''),
              name: store.name,
              enabled: true,
              latitude: parseFloat(store.lat),
              longitude: parseFloat(store.lng),
              country_id: store.country,
              region_id: store.region_id,
              city: store.city,
              postcode: store.zip,
              street: store.address,
              description: store.description,
              use_default_carrier_config: true,
              email:store.email
         
            }
      };

      try {
        const response = await axios.post(magentoApiEndpoint, sourceData, config);
        console.log(`Successfully created source: ${response.data.name}`);
      } catch (error) {
        console.error(`Failed to create source for ${store.name}:`, error.response?.data?.message || error.message);
      }
    }
  } catch (error) {
    console.error('Error during authentication or API request:', error.message);
  }
}

createMagentoSources();
